site_name: Zhenhua's Notes
site_description: Zhenhua's Notes
site_url: http://larryim.cc/note-os/
site_author: Zhenhua Wang
lang: Japanese

#repo_url: https://github.com/techlarry/note
theme: 
    name: flatly
    #custom_dir: 'custom_theme'
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - extra_javascript/tabhack.js
    - extra_javascript/baidu.js


extra_css:
    - extra_css/custom.css
    - extra_css/custom.js
    - extra_css/friendly.css
    - extra_css/theme.css
    - extra_css/mkdocs/js/lunr-0.5.7.min.js
    - extra_css/mkdocs/js/mustache.min.js
    - extra_css/mkdocs/js/require.js
    - extra_css/mkdocs/js/search.js
    - extra_css/mkdocs/js/text.js
    - extra_css/code-tab.css


markdown_extensions:
    - pymdownx.inlinehilite ## https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
    - pymdownx.arithmatex
    - pymdownx.critic
    - admonition
    - codehilite ## https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
    - toc:
        permalink: True
    - markdown_fenced_code_tabs: # https://github.com/yacir/markdown-fenced-code-tabs/tree/1.0.0
        single_block_as_tab: False
        template: 'default'

      
nav:
    - Home: 'index.md'
#    - APUE:
#        - 'Contents': 'apue/index.md'
#        - 'Chapter 1. UNIX System Overview': 'apue/ch1.md'
#        - 'Chapter 2. UNIX Standardization and Implementations': 'apue/ch2.md'
#        - 'Chapter 3. File I/O': 'apue/ch3.md'
#        - 'Chapter 4. Files and Directories': 'apue/ch4.md'
#        - 'Chapter 5. Standard I/O Library': 'apue/ch5.md'
#        - 'Chapter 6. System Data Files and Information': 'apue/ch6.md'
#        - 'Chapter 7. Process Environment': 'apue/ch7.md'
#        - 'Chapter 8. Process Control': 'apue/ch8.md'
#        - 'Chapter 9. Process Relationships': 'apue/ch9.md'
#        - 'Chapter 10. Signals': 'apue/ch10.md'
#        - 'Chapter 11. Threads': 'apue/ch11.md'
#        - 'Chapter 12. Thread Control': 'apue/ch12.md'
#        - 'Chapter 13. Daemon Processes': 'apue/ch13.md'
#        - 'Chapter 14. Advanced I/O': 'apue/ch14.md'
#        - 'Chapter 15. Interprocess Communication': 'apue/ch15.md'
#        - 'Chapter 16. Network IPC: Sockets': 'apue/ch16.md'
#        - 'Chapter 17. Advanced IPC': 'apue/ch17.md'
    
    - Algorithm:
        - 'Contents': 'algorithm/index.md'
        - AlgorithmPrinceton:    
            - 'Contents': 'algorithm/algorithmPrinceton/index.md'
            - 'Topic 1: UnionFind' : 'algorithm/algorithmPrinceton/unionfind.md'
            - 'Topic 2: StackQueue' : 'algorithm/algorithmPrinceton/stackqueue.md'
            - 'Topic 3: Sort' : 'algorithm/algorithmPrinceton/sort.md'
            - 'Topic 4: PriorityQueues' : 'algorithm/algorithmPrinceton/priorityqueue.md'   
            - 'Topic 5: Symbol Tables' : 'algorithm/algorithmPrinceton/symboltable.md'   
            - 'Topic 6: Balanced Search Trees' : 'algorithm/algorithmPrinceton/bst.md'   
            - 'Topic 7: Hash Table' : 'algorithm/algorithmPrinceton/hashtable.md'   
            - 'Topic 8: Graph' : 'algorithm/algorithmPrinceton/graph.md'   
            - 'Topic 9: Minimum Spanning Tree and Shortest Path' : 'algorithm/algorithmPrinceton/mst_shortestpath.md'   
            - 'Topic 11: String Sort' : 'algorithm/algorithmPrinceton/stringsort.md'   
            - 'Topic 12: Tries' : 'algorithm/algorithmPrinceton/tries.md'   



        - AlgorithmStanford:
            - 'Contents': 'algorithm/algorithmStanford/index.md'
            - 'Topic: Dynammic Programming' : 'algorithm/algorithmStanford/dynamicprogramming.md'
            - 'Topic: Heap' : 'algorithm/algorithmStanford/heap.md'
            - 'Topic: Graph' : 'algorithm/algorithmStanford/graph.md'
            - 'Topic: Greedy Algorithm' : 'algorithm/algorithmStanford/greedy.md'
            - 'Topic: Hash Table' : 'algorithm/algorithmStanford/hashtable.md'

        - CS61B:
            - 'Contents': 'algorithm/cs61b/index.md'
            - 'Lab1: javac, java, git' : 'algorithm/cs61b/Lab1.md'
            - 'Lab2: Unit Testing with JUnit and IntLists' : 'algorithm/cs61b/Lab2.md'
            - 'Lab3: Unit Testing with JUnit, Debugging' : 'algorithm/cs61b/Lab3.md' 
        
        - Sword:
            - 'Contents': 'algorithm/sword/index.md'
            - '⾯试需要的基础知识': 'algorithm/sword/ch2.md'
            - '高质量的代码': 'algorithm/sword/ch3.md'
            - '解决面试题的思路': 'algorithm/sword/ch4.md'
            - '优化时间和空间效率': 'algorithm/sword/ch5.md'
            - '面试中的各项能力': 'algorithm/sword/ch6.md'
            - '两个面试案例': 'algorithm/sword/ch7.md'

    - OS:
        - 'Contents': 'os/index.md'
        - OSC:
            - 'Contents': 'os/osc/index.md'
            - 'Chapter 1: Introduction ' : 'os/osc/ch1.md'
            - 'Chapter 2: Operating System structures' : 'os/osc/ch2.md'
            - 'Chapter 3: Processes' : 'os/osc/ch3.md'
            - 'Chapter 4: Threads and Concurrency' : 'os/osc/ch4.md'
            - 'Chapter 5: CPU Scheduling' : 'os/osc/ch5.md'
            - 'Chapter 6: Synchronization Tools' : 'os/osc/ch6.md'
            - 'Chapter 7: Synchronization Examples' : 'os/osc/ch7.md'
            - 'Chapter 8: Deadlocks' : 'os/osc/ch8.md'
            - 'Chapter 9: Main Memory' : 'os/osc/ch9.md'
            - 'Chapter 10: Virtual Memory' : 'os/osc/ch10.md'
            - 'Chapter 11: Mass-Storage Structure' : 'os/osc/ch11.md'
            - 'Chapter 13: File-System Interfaces' : 'os/osc/ch13.md'
        
        - CSAPP:
            - 'Contents': 'os/csapp/index.md'
            - 'Chapter 1: 计算机系统漫游' : 'os/csapp/ch1.md'
            - 'Chapter 2: 信息的表示和处理' : 'os/csapp/ch2.md'
            - 'Chapter 3: 程序的机器级表示' : 'os/csapp/ch3.md'
            - 'Chapter 4: 处理器体系结构' : 'os/csapp/ch4.md'
            - 'Chapter 5: 优化程序性能' : 'os/csapp/ch5.md'
            - 'Chapter 6: 存储器层次结构' : 'os/csapp/ch6.md'
            - 'Chapter 7: 链接' : 'os/csapp/ch7.md'
            - 'Chapter 8: 异常控制流' : 'os/csapp/ch8.md'
            - 'Chapter 9: 虚拟内存' : 'os/csapp/ch9.md'
            - 'Chapter 10: 系统级I/O' : 'os/csapp/ch10.md'
            - 'Chapter 11: 网络编程' : 'os/csapp/ch11.md'

    - DataBase:
        - 'Contents': 'database/index.md'
        - MySql:
            - 'Contents': 'database/mysql/index.md'
            - 'Chapter Learning MySQL and MariaDB' : 'database/mysql/LearningMySQLandMariaDB.md'

    - Java:
        - 'Contents': 'java/index.md'
        - HFJ:
            - 'Contents': 'java/hfj/index.md'
            - 'Chapter 1: Dive in A Quick Dip' : 'java/hfj/ch1.md'
            - 'Chapter 2: Classes and Objects' : 'java/hfj/ch2.md'
            - 'Chapter 3: Primitives and References' : 'java/hfj/ch3.md'
            - 'Chapter 4: Methods use Instance Variables' : 'java/hfj/ch4.md'
            - 'Chapter 5: Writing a Program' : 'java/hfj/ch5.md'
            - 'Chapter 6: Get to Know the Java API' : 'java/hfj/ch6.md'
            - 'Chapter 7: Inheritance and Polymorphism' : 'java/hfj/ch7.md'
            - 'Chapter 8: Interfaces and Abstract Classes' : 'java/hfj/ch8.md'
            - 'Chapter 9: Constructors and Garbage Collection' : 'java/hfj/ch9.md'
            - 'Chapter 10: Numbers and Statics' : 'java/hfj/ch10.md'
            - 'Chapter 11: Exception Handling' : 'java/hfj/ch11.md'
            - 'Chapter 12: Getting GUI' : 'java/hfj/ch12.md'
            - 'Chapter 13: Using Swing' : 'java/hfj/ch13.md'
            - 'Chapter 14: Serialization and File I/O' : 'java/hfj/ch14.md'
            - 'Chapter 15: Networking and Threads' : 'java/hfj/ch15.md'
            - 'Chapter 16: Collections and Generics' : 'java/hfj/ch16.md'
            - 'Chapter 17: Packages, Jars and Deployment' : 'java/hfj/ch17.md'
            - 'Chapter 18: Remote deploy with RMI' : 'java/hfj/ch18.md'
            - 'Appendix: The Top Ten Topics' : 'java/hfj/Appendix.md'
        
        - HFDP:
            - 'Contents': 'java/hfdp/index.md'
            - 'Chapter 1: Strategy Pattern ' : 'java/hfdp/ch1.md'
            - 'Chapter 2: Observer Pattern' : 'java/hfdp/ch2.md'
            - 'Chapter 3: Decorator Pattern ' : 'java/hfdp/ch3.md'
            - 'Chapter 4: Factory Pattern' : 'java/hfdp/ch4.md'
            - 'Chapter 5: Singleton Pattern' : 'java/hfdp/ch5.md'
            - 'Chapter 6: Command Pattern' : 'java/hfdp/ch6.md'
            - 'Chapter 7: Adapter and Facade Patterns' : 'java/hfdp/ch7.md'
            - 'Chapter 8: Template Method Pattern' : 'java/hfdp/ch8.md'
            - 'Chapter 9: Iterator and Composite Patterns' : 'java/hfdp/ch9.md'
            #- 'Chapter 10: State Pattern' : 'hfdp/ch10.md'
            #- 'Chapter 11: Proxy Pattern' : 'hfdp/ch11.md'
            #- 'Chapter 12: Compound Pattern' : 'hfdp/ch12.md'
            #- 'Chapter 13: Better Living with Patterns' : 'hfdp/ch13.md'
        
        - MultiThreading:
            - 'Contents': 'java/multithreading/index.md'
            - '序章1 Java线程' : 'java/multithreading/pre1.md'
            - '序章2 多线程程序的评价标准' : 'java/multithreading/pre2.md'
            - '第1章 Single Threaded Execution模式' : 'java/multithreading/ch1.md'
            - '第2章 Immutable模式' : 'java/multithreading/ch1.md'


        - TIJ:
            - 'Contents': 'java/tij/index.md'
            - 'Chapter 1: Introduction' : 'java/tij/ch1.md'
            - 'Chapter 2: Introduction to Objects' : 'java/tij/ch2.md'
            - 'Chapter 3: Everything is an Object' : 'java/tij/ch3.md'
            - 'Chapter 4: Opertors' : 'java/tij/ch4.md'
            - 'Chapter 5: Controlling Execution' : 'java/tij/ch5.md'
            - 'Chapter 6: Initialization & Cleanup' : 'java/tij/ch6.md'
            - 'Chapter 7: Access Control' : 'java/tij/ch7.md'
            - 'Chapter 8: Reusing Clases' : 'java/tij/ch8.md'
            - 'Chapter 9: Polymorphism' : 'java/tij/ch9.md'
            - 'Chapter 10: Interfaces' : 'java/tij/ch10.md'
            - 'Chapter 11: Inner Classes' : 'java/tij/ch11.md'
            - 'Chapter 12: Holding Your Objects' : 'java/tij/ch12.md'
            - 'Chapter 13: Error Handling with Exceptions' : 'java/tij/ch13.md'
            - 'Chapter 14: Strings' : 'java/tij/ch14.md'
            - 'Chapter 15: Type Information' : 'java/tij/ch15.md'
            - 'Chapter 16: Generics' : 'java/tij/ch16.md'
            - 'Chapter 17: Arrays' : 'java/tij/ch17.md'
            - 'Chapter 18: Containers in Depth' : 'java/tij/ch18.md'
            - 'Chapter 19: I/O' : 'java/tij/ch19.md'
            - 'Chapter 20: Enumerated Types' : 'java/tij/ch20.md'
            - 'Chapter 21: Annotations' : 'java/tij/ch21.md'
            - 'Chapter 22: Concurrency' : 'java/tij/ch22.md'
            - 'Chapter 23: Graphical User Interfaces' : 'java/tij/ch23.md'

    # - CPJ:
    #     - 'Contents': 'cpj/index.md'
    #     - 'Concurrent Programming in Java 1: Threads and Locks' : 'cpj/ch1.md'
    #     - 'Concurrent Programming in Java 2: Critical Sections and Isolation' : 'cpj/ch2.md'
    #     - 'Concurrent Programming in Java 3: Actors' : 'cpj/ch3.md'
    #     - 'Concurrent Programming in Java 4: Concurrent Data Structures' : 'cpj/ch4.md'



    # - LKD:
    #     - 'Contents': 'lkd/index.md'
    #     - 'Chapter 1 : Introduction to Linux Kernel': 'lkd/ch1.md'
    #     - 'Chapter 2': 'lkd/ch2.md'
    #     - 'Chapter 3': 'lkd/ch3.md'
    #     - 'Chapter 4': 'lkd/ch4.md'
    #     - 'Chapter 5': 'lkd/ch5.md'
    #     - 'Chapter 6': 'lkd/ch6.md'
    #     - 'Chapter 7': 'lkd/ch7.md'
    #     - 'Chapter 8': 'lkd/ch8.md'
    #     - 'Chapter 9': 'lkd/ch9.md'
    #     - 'Chapter 10': 'lkd/ch10.md'
    #     - 'Chapter 11': 'lkd/ch11.md'
    #     - 'Chapter 12: Memory management': 'lkd/ch12.md'
    #     - 'Chapter 13': 'lkd/ch13.md'
    #     - 'Chapter 14': 'lkd/ch14.md'
    #     - 'Chapter 15': 'lkd/ch15.md'
    #     - 'Chapter 16': 'lkd/ch16.md'
    #     - 'Chapter 17': 'lkd/ch17.md'
    #     - 'Chapter 18': 'lkd/ch18.md'
    #     - 'Chapter 19': 'lkd/ch19.md'
    #     - 'Chapter 20': 'lkd/ch20.md'
        - UJVM:
            - 'Contents' : 'java/ujvm/index.md'
            - 'Chapter 1 : 走进Java': 'java/ujvm/ch1.md' 
            - 'Chapter 2 : Java内存区域与内存溢出正常': 'java/ujvm/ch2.md'
            - 'Chapter 3 : 垃圾收集器与内存分配策略': 'java/ujvm/ch3.md'
            - 'Chapter 4 : 虚拟机性能监控与故障处理工具': 'java/ujvm/ch4.md'
            - 'Chapter 5 : 调优案例分析与实战': 'java/ujvm/ch5.md'
            - 'Chapter 6 : 类文件结构': 'java/ujvm/ch6.md'
            - 'Chapter 7 : 虚拟机类加载机制': 'java/ujvm/ch7.md'
            - 'Chapter 8 : 虚拟机字节码执行引擎': 'java/ujvm/ch8.md'
            - 'Chapter 9 : 类加载及执行子系统的案例与实战': 'java/ujvm/ch9.md'
            - 'Chapter 10 : 早期(编译期)优化': 'java/ujvm/ch10.md'
            - 'Chapter 11 : 晚期(运行期)优化': 'java/ujvm/ch11.md'
            - 'Chapter 12 : Java内存模型与线程': 'java/ujvm/ch12.md'
            - 'Chapter 13 : 线程安全与锁优化': 'java/ujvm/ch13.md'
            - 'Appendix HotSpot虚拟机主要参数列表': 'java/ujvm/AppendixC.md'

    - BigData:
        - 'Contents': 'bigdata/index.md'
        - HADOOP:
            - 'Contents': 'bigdata/hadoop/index.md'
            - 'Chapter 1: Meet Hadoop' : 'bigdata/hadoop/ch1.md'
            - 'Chapter 2: MapReduce' : 'bigdata/hadoop/ch2.md'
            - 'Chapter 3: The Hadoop Distributed FileSystem' : 'bigdata/hadoop/ch3.md'
            - 'Chapter 4: YARN' : 'bigdata/hadoop/ch4.md'
            - 'Chapter 5: Hadoop I/O' : 'bigdata/hadoop/ch5.md'
            - 'Chapter 6: Developing a MapReduce Application' : 'bigdata/hadoop/ch6.md'
            - 'Chapter 7: How MapReduce Works' : 'bigdata/hadoop/ch7.md'
            - 'Chapter 8: MapReduce Types and Formats' : 'bigdata/hadoop/ch8.md'
            - 'Chapter 9: MapReduce Features' : 'bigdata/hadoop/ch9.md'
            - 'Chapter 10: Setting Up a Hadoop Cluster' : 'bigdata/hadoop/ch10.md'
            - 'Chapter 11: Adminstering Hadoop' : 'bigdata/hadoop/ch11.md'
            - 'Chapter 12: Avro' : 'bigdata/hadoop/ch12.md'
            - 'Chapter 13: Parquet' : 'bigdata/hadoop/ch13.md'
            - 'Chapter 14: Flume' : 'bigdata/hadoop/ch14.md'
            - 'Chapter 15: Sqoop' : 'bigdata/hadoop/ch15.md'
            - 'Chapter 16: Pig' : 'bigdata/hadoop/ch16.md'
            - 'Chapter 17: Hive' : 'bigdata/hadoop/ch17.md'
            - 'Chapter 18: Crunch' : 'bigdata/hadoop/ch18.md'
            - 'Chapter 19: Spark' : 'bigdata/hadoop/ch19.md'
            - 'Chapter 20: HBase' : 'bigdata/hadoop/ch20.md'
            - 'Chapter 21: ZooKeeper' : 'bigdata/hadoop/ch21.md'
            - 'Chapter 22: Composable Data at Center' : 'bigdata/hadoop/ch22.md'
            - 'Chapter 23: Biological Data Science: Saving Lives with Software' : 'bigdata/hadoop/ch23.md'
            - 'Chapter 24: Cascading' : 'bigdata/hadoop/ch24.md'

        - Spark:
            - 'Contents': 'bigdata/spark/index.md'
            - 'Chapter 1: Introduction to Data Analysis with Spark' : 'bigdata/spark/ch1.md'
            - 'Chapter 2: Downloading Spark and Getting Started' : 'bigdata/spark/ch2.md'
            - 'Chapter 3: Programming with RDDs' : 'bigdata/spark/ch3.md'
            - 'Chapter 4: Working with Key/Value Pairs' : 'bigdata/spark/ch4.md'
            - 'Chapter 5: Loading and Saving Your Data' : 'bigdata/spark/ch5.md'
            - 'Chapter 6: Advanced Spark Programming' : 'bigdata/spark/ch6.md'
            - 'Chapter 7: Running on a Cluster' : 'bigdata/spark/ch7.md'
            - 'Chapter 8: Tuning and Debugging Spark' : 'bigdata/spark/ch8.md'
            - 'Chapter 9: Spark SQL' : 'bigdata/spark/ch9.md'
            - 'Chapter 10: Spark Streaming' : 'bigdata/spark/ch10.md'
            - 'Chapter 11: Machine Learning with MLlib' : 'bigdata/spark/ch11.md'


        - GDM:
            - 'Contents': 'bigdata/gdm/index.md'
            - 'Chapter 1: 推荐系统入门' : 'bigdata/gdm/ch1.md'
            - 'Chapter 2: 隐式评价和基于物品的过滤算法' : 'bigdata/gdm/ch2.md'
            - 'Chapter 3: 分类' : 'bigdata/gdm/ch3.md'
            - 'Chapter 4: 进一步探索分类' : 'bigdata/gdm/ch4.md'
            - 'Chapter 5: 概率和朴素贝叶斯' : 'bigdata/gdm/ch5.md'
            - 'Chapter 6: 朴素贝叶斯和文本数据' : 'bigdata/gdm/ch6.md'
            - 'Chapter 7: 聚类' : 'bigdata/gdm/ch7.md'
            
        - MLIA:
            - 'Contents': 'bigdata/mlia/index.md'
            - 'Chapter 1: 机器学习基础' : 'bigdata/mlia/ch1.md'
            - 'Chapter 2: k-近邻算法' : 'bigdata/mlia/ch2.md'
            - 'Chapter 3: 决策树' : 'bigdata/mlia/ch3.md'
            - 'Chapter 4: 基于概率论的分类方法：朴素贝叶斯' : 'bigdata/mlia/ch4.md'
            - 'Chapter 5: Logistic回归' : 'bigdata/mlia/ch5.md'
            - 'Chapter 6: 支持向量机' : 'bigdata/mlia/ch6.md'
            - 'Chapter 7: 利用AdaBoost元算法提高分类性能' : 'bigdata/mlia/ch7.md'
            - 'Chapter 8: 预测数值型数据：回归' : 'bigdata/mlia/ch8.md'
            - 'Chapter 9: 树回归' : 'bigdata/mlia/ch9.md'
            - 'Chapter 10: 利用Ｋ-均值聚类算法对未标注数据分组' : 'bigdata/mlia/ch10.md'
            - 'Chapter 11: 使用Apriori算法进行关联分析' : 'bigdata/mlia/ch11.md'
            - 'Chapter 12: 使用FP-growth算法来高效发现频繁项集' : 'bigdata/mlia/ch11.md'
            - 'Chapter 13: 利用PCA来简化数据' : 'bigdata/mlia/ch13.md'

        #- PROB:
        #    - 'Contents': 'prob/index.md'
        #    - 'Chapter 1: 样本空间和概率' : 'prob/ch1.md'

        - Crawler:
            - 'Contents': 'bigdata/crawler/index.md'
            - 'Chapter 1: 开发环境配置': 'bigdata/crawler/ch1.md'
            - 'Chapter 2: 爬虫基础': 'bigdata/crawler/ch2.md'
            - 'Chapter 3: 基本库的使用': 'bigdata/crawler/ch3.md'
            - 'Chapter 4: 解析库的使用': 'bigdata/crawler/ch4.md'
            - 'Chapter 5: 数据存储': 'bigdata/crawler/ch5.md'
            - 'Chapter 7: 动态渲染页面爬取': 'bigdata/crawler/ch7.md'
            - 'Chapter 13: Scrapy框架的使用': 'bigdata/crawler/ch13.md'

        
        - Projects:
            - 'Contents': 'bigdata/projects/index.md'
            - 'SparkStreaming实时流处理': 'bigdata/projects/SparkStreaming实时流处理项目.md'

    - Books: 'books.md'
    
